// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.easybi.domain;

import org.easybi.domain.PizzaOrderIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PizzaOrderIntegrationTest_Roo_Configurable {
    
    declare @type: PizzaOrderIntegrationTest: @Configurable;
    
}
